name: tmp

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check ip
        run: curl -sS https://checkip.amazonaws.com/

      - name: gdpr test
        run: curl -vsS --fail-with-body https://invalid.yahoo.co.jp/
